# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-s5tjrVjZmHz59NTTezJikanRUWx5NT
"""

pip install mlflow==2.19.0

import mlflow

print(mlflow.__version__)

# Import Library

import pandas as pd
import mlflow
import mlflow.sklearn

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Load Dataset Hasil Preprocessing

df = pd.read_csv("bank_marketing_preprocessing.csv")

df.head()

df.shape

# Memisahkan fitur dan target

X = df.drop("deposit", axis=1)
y = df["deposit"]

# Split dataset

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

# Mengaktifkan MLflow Autolog

mlflow.autolog()

# Training model

with mlflow.start_run():

    model = RandomForestClassifier(
        random_state=42
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print("Accuracy :", accuracy)
    print("Precision:", precision)
    print("Recall   :", recall)
    print("F1 Score :", f1)

# Mengecek Apakah MLflow Menyimpan Run

# !ls mlruns

